# Generated by Django 2.1b1 on 2018-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('date_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
